## Exemplo da última aula


Considere um objeto descrevendo um movimento retilínio uniformemente variado (MRUV) ao longo do eixo $x$.
A posição ao longo do eixo $x$ em função do tempo é dada por:

\begin{equation}
x(t) = x_0 + v_0 t + \frac{a t^2}{2}
\end{equation}

e a velocidade em função do tempo é dada por:

$$ v(t) = v_0 + at $$



Criando funções para determinar a posição e velocidade do objeto:


In [1]:
def posicao(t, a, x0=0., v0=0.):
  """Determina a posição de um objeto que descreve MRUV."""
  x = x0 + v0*t + a*t**2/2
  return x

In [2]:
def velocidade(t, a, v0=0.):
  """Determina a velocidade de um objeto que descreve MRUV."""
  v = v0 + a*t
  return v

Podemos usar as funções para encontrar a posição e velocidade para valores específicos.

Por exemplo, considerando que objeto partiu da origem ($x_0=0$) com velocidade inicial $v_0=0$ e aceleração $a = 5$ m/s$^2$, no tempo $t = 10$ s a sua posição e velocidade serão

In [3]:
t = 10.
a = 5.
print(posicao(t,a))
print(velocidade(t, a))

250.0
50.0


Determinando as posições para $a = 5$ m/s$^2$ e t variando de 0 a 50s em intervalos de 1s usando listas

In [4]:
lista_posicoes = []
for t in range(51):
  lista_posicoes.append(posicao(t,a=5.))

print(lista_posicoes)

[0.0, 2.5, 10.0, 22.5, 40.0, 62.5, 90.0, 122.5, 160.0, 202.5, 250.0, 302.5, 360.0, 422.5, 490.0, 562.5, 640.0, 722.5, 810.0, 902.5, 1000.0, 1102.5, 1210.0, 1322.5, 1440.0, 1562.5, 1690.0, 1822.5, 1960.0, 2102.5, 2250.0, 2402.5, 2560.0, 2722.5, 2890.0, 3062.5, 3240.0, 3422.5, 3610.0, 3802.5, 4000.0, 4202.5, 4410.0, 4622.5, 4840.0, 5062.5, 5290.0, 5522.5, 5760.0, 6002.5, 6250.0]


In [7]:
# podemos converter uma lista para um array
import numpy as np
posicoes_array = np.array(lista_posicoes)
print(posicoes_array)

[0.0000e+00 2.5000e+00 1.0000e+01 2.2500e+01 4.0000e+01 6.2500e+01
 9.0000e+01 1.2250e+02 1.6000e+02 2.0250e+02 2.5000e+02 3.0250e+02
 3.6000e+02 4.2250e+02 4.9000e+02 5.6250e+02 6.4000e+02 7.2250e+02
 8.1000e+02 9.0250e+02 1.0000e+03 1.1025e+03 1.2100e+03 1.3225e+03
 1.4400e+03 1.5625e+03 1.6900e+03 1.8225e+03 1.9600e+03 2.1025e+03
 2.2500e+03 2.4025e+03 2.5600e+03 2.7225e+03 2.8900e+03 3.0625e+03
 3.2400e+03 3.4225e+03 3.6100e+03 3.8025e+03 4.0000e+03 4.2025e+03
 4.4100e+03 4.6225e+03 4.8400e+03 5.0625e+03 5.2900e+03 5.5225e+03
 5.7600e+03 6.0025e+03 6.2500e+03]


Operações com arrays - **muito mais simples**!!!


In [8]:
import numpy as np
t_a = np.arange(0,51,1)
pos = posicao(t_a, a=5.)
print(t_a)
print(pos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[0.0000e+00 2.5000e+00 1.0000e+01 2.2500e+01 4.0000e+01 6.2500e+01
 9.0000e+01 1.2250e+02 1.6000e+02 2.0250e+02 2.5000e+02 3.0250e+02
 3.6000e+02 4.2250e+02 4.9000e+02 5.6250e+02 6.4000e+02 7.2250e+02
 8.1000e+02 9.0250e+02 1.0000e+03 1.1025e+03 1.2100e+03 1.3225e+03
 1.4400e+03 1.5625e+03 1.6900e+03 1.8225e+03 1.9600e+03 2.1025e+03
 2.2500e+03 2.4025e+03 2.5600e+03 2.7225e+03 2.8900e+03 3.0625e+03
 3.2400e+03 3.4225e+03 3.6100e+03 3.8025e+03 4.0000e+03 4.2025e+03
 4.4100e+03 4.6225e+03 4.8400e+03 5.0625e+03 5.2900e+03 5.5225e+03
 5.7600e+03 6.0025e+03 6.2500e+03]


Calculando a posição para tempo de 0 s a 50 s a cada 2.5 s para $a=5$ m/s$^2$, $x_0 = 0$ m $v_0 = 10$ m/s

In [9]:
t = np.arange(0,52.5,2.5)
print(t)
pos = posicao(t, a=5., v0=10.)

print(pos)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5
 35.  37.5 40.  42.5 45.  47.5 50. ]
[   0.      40.625  112.5    215.625  350.     515.625  712.5    940.625
 1200.    1490.625 1812.5   2165.625 2550.    2965.625 3412.5   3890.625
 4400.    4940.625 5512.5   6115.625 6750.   ]


Determinando a velocidade para tempo de 0 s a 50 s a cada 0.5 s para $a=5$ m/s$^2$, $x_0 = 0$ m $v_0 = 10$ m/s

In [10]:
vel = velocidade(t,a=5., v0=10.)
print(vel)

[ 10.   22.5  35.   47.5  60.   72.5  85.   97.5 110.  122.5 135.  147.5
 160.  172.5 185.  197.5 210.  222.5 235.  247.5 260. ]


# Arrays


Um array é uma estrutura de dados que armazena um conjunto ordenado de elementos, todos do mesmo tipo.

In [12]:
# Criando um array NumPy unidimensional
a = np.array([1, 2, 3, 4])
print(a)

# Operações com arrays
print(a * 2)  # Saída:

# Criando um array multidimensionais (matriz)
b = np.array([[1, 2], [3, 4]])
print(b)

[1 2 3 4]
[2 4 6 8]
[[1 2]
 [3 4]]


**Outras formas de criar arrays**


np.zeros(shape): cria array com todos os elementos iguais a zero, onde shape é o formato do array

In [15]:
a0 = np.zeros(10, dtype = int)  # Array 1D com 10 zeros do tipo inteiro
print(a0)

[0 0 0 0 0 0 0 0 0 0]


In [14]:
a0_2 = np.zeros((3,2,5)) # Array 3D com tamanho 3x2x5
print(a0_2)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


np.ones(shape): cria um array com todos os elementos iguais a 1, , onde shape é o formato do array



In [ ]:
a1 = np.ones(7) # Array 1D com 7 elementos
print(a1)

[1. 1. 1. 1. 1. 1. 1.]


In [16]:
a1_2 = np.ones((2,3),dtype=int) # Array 2D (matriz) 2x3 com 1s do tipo inteiro
print(a1_2)

[[1 1 1]
 [1 1 1]]


In [18]:
a1_3 = np.ones((3,2,3,4)) # Array 4D (matriz) 3x2x3x4
print(a1_3)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


np.full(shape, valor): cria um array preenchido com um valor específico

In [20]:
a3 = np.full((4,2), 3)  # Array 4x2 preenchida com 3
print(a3)

[[3 3]
 [3 3]
 [3 3]
 [3 3]]


np.arange(início, fim, passo): cria um array com valores em uma sequência regular. O valor de início é incluído e o do fim é excluído. É parecida com range() do Python, mas o passo não precisa ser um inteiro.

In [22]:
a4 = np.arange(0, 10, 2.5)
print(a4)

[0.  2.5 5.  7.5]


np.linspace(início, fim, n): Cria um array com n valores igualmente espaçados entre o início (incluído) e fim (incluído também).

In [24]:
a5 = np.linspace(0, 1, 6)
print(a5)

[0.  0.2 0.4 0.6 0.8 1. ]


np.eye(n): cria uma matriz identidade de tamanho n x n.

In [26]:
a_i = np.eye(5)

print(a_i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


O NumPy também oferece várias funções para criar arrays com números aleatórios, muito úteis em simulações, testes e experimentos numéricos.

Estes métodos estão incluídos no módulo numpy.random.

np.random.rand(d1, d2, ...): cria um array com números aleatórios uniformemente distribuídos no intervalo [0, 1), onde d1, d2, etc são as dimensões


In [28]:
a_r = np.random.rand(2,4,5)  # matriz 2x4x5 com números aleatórios no intervalo [0,1)
print(a_r)

[[[0.31888232 0.50306473 0.27877516 0.98661372 0.95092932]
  [0.27749316 0.212917   0.47440781 0.57683294 0.5996716 ]
  [0.14264308 0.15400663 0.32643044 0.96467503 0.53354013]
  [0.26179239 0.7624202  0.23319311 0.88635579 0.74710689]]

 [[0.76842221 0.79100238 0.51090667 0.09830958 0.89174813]
  [0.95557566 0.17587018 0.03762784 0.78777083 0.71835813]
  [0.85692805 0.39116489 0.73688039 0.45012522 0.09781707]
  [0.17924502 0.78760003 0.87592311 0.09959253 0.24987483]]]


np.random.randint(início, fim, size): cria um array com números inteiros aleatórios no intervalo [início, fim) e com tamanho igual a size

In [30]:
a_r2 = np.random.randint(1, 7, size=(2,3))  # matriz 2x3 com inteiros entre 1 e 6
print(a_r2)

[[2 1 2]
 [3 5 2]]


**Cuidado** ao fazer cópias de arrays

In [ ]:
a = np.array([1,1])
print(a)
b = a
print(b == a)
a[0] = 2
print(a)
print(b)

[1 1]
[ True  True]
[2 1]
[2 1]


In [ ]:
a is b

True

In [ ]:
a = np.array([1,1])
b = np.copy(a)  # np.copy cria uma cópia do array
a[0] = 2
print(a)
print(b)

[2 1]
[1 1]


In [ ]:
a is b

False

**Operações com arrays**

O poder do Numpy vem da possibilidade de realizar operações com arrays.

Com np.array, as operações são feitas elemento a elemento, sem precisar de loop for:

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Soma: [5 7 9]
print(a - b)   # Subtração: [-3 -3 -3]
print(a * b)   # Multiplicação: [ 4 10 18]
print(b / a)   # Divisão: [4.  2.5 2. ]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]


Operação com escalares:

In [33]:
print(a + 5)    # Soma: [6 7 8]
print(a * 2)    # Multiplicação: [2 4 6]

[6 7 8]
[2 4 6]


O NumPy fornece funções que atuam sobre arrays inteiros:

In [35]:
print(np.sin(a))
print(np.exp(a))
print(np.sqrt(a))

[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]


 O NumPy fornece funções que realizam a soma, média e estatísticas dos elementos de um array:

In [36]:
print(a.sum())       # soma dos elementos
print(a.mean())      # média dos elementos
print(a.max())       # maior valor do array
print(a.min())       # menor valor do array
print(a.std())       # desvio padrão dos elementos

6
2.0
3
1
0.816496580927726


Funções para realizar operações com matrizes (arrays 2D)


In [38]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

print(np.dot(A, B)) # Produto matricial

[[ 70 100]
 [150 220]]


Comparações e filtros lógicos

In [40]:
a = np.array([5, 10, 15, 20])

print(a > 10)        # [False False  True  True]
print(a[a > 10])     # filtrando os elementos que são > 10

[False False  True  True]
[15 20]
